<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>Streamline.Engine.Tests</AssemblyName>
    <RootNamespace>Streamline.Engine.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Streamline.Api\Streamline.Api.csproj" />
    <ProjectReference Include="..\..\src\Streamline.Application\Streamline.Application.csproj" />
    <ProjectReference Include="..\..\src\Streamline.Infrastructure\Streamline.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Streamline.Domain\Streamline.Domain.csproj" />
    <ProjectReference Include="..\..\src\Streamline.Engine\Streamline.Engine\Streamline.Engine.csproj" />
  </ItemGroup>

</Project>
