namespace Streamline.DSL.CodeAnalysis.Bpmn;

public static class SyntaxFactory
{
    private static readonly Dictionary<string, SyntaxKind> Keywords = new(StringComparer.OrdinalIgnoreCase)
    {
        { "Asterix", SyntaxKind.AsterixToken },
        { "Association", SyntaxKind.AssociationElement },
        { "AssociationDirection", SyntaxKind.BpmnAttributeToken },
        { "AttachedToRef", SyntaxKind.BpmnAttributeToken },
        { "BadToken", SyntaxKind.BadToken },
        { "BoundaryEvent", SyntaxKind.BoundaryEventElement },
        { "BusinessRuleTask", SyntaxKind.BusinessRuleTaskElement },
        { "CallActivity", SyntaxKind.CallActivityElement },
        { "CalledElement", SyntaxKind.BpmnAttributeToken },
        { "CancelActivity", SyntaxKind.BpmnAttributeToken },
        { "CancelRemainingInstances", SyntaxKind.BpmnAttributeToken },
        { "CategoryValueRef", SyntaxKind.BpmnAttributeToken },
        { "CloseBrace", SyntaxKind.CloseBraceToken },
        { "CloseParenthesis", SyntaxKind.CloseParenthesisToken },
        { "Comma", SyntaxKind.CommaToken },
        { "Compensation", SyntaxKind.CompensationEventElement },
        { "ConditionExpression", SyntaxKind.BpmnAttributeToken },
        { "Conditional", SyntaxKind.ConditionalEventElement },
        { "CompletionCondition", SyntaxKind.BpmnAttributeToken },
        { "CompletionQuantity", SyntaxKind.BpmnAttributeToken },
        { "DataAssociation", SyntaxKind.DataAssociationElement },
        { "DataInput", SyntaxKind.DataInputElement },
        { "DataObject", SyntaxKind.DataObjectElement },
        { "DataOutput", SyntaxKind.DataOutputElement },
        { "DataStore", SyntaxKind.DataStoreElement },
        { "Default", SyntaxKind.BpmnAttributeToken },
        { "Definition", SyntaxKind.BpmnAttributeToken },
        { "Division", SyntaxKind.DivisionToken },
        { "EndEvent", SyntaxKind.EndEventElement },
        { "EndOfFile", SyntaxKind.EndOfFileToken },
        { "Equals", SyntaxKind.EqualsToken },
        { "Error", SyntaxKind.ErrorEventElement },
        { "ErrorEvent", SyntaxKind.ErrorEventElement },
        { "Escalation", SyntaxKind.EscalationEventElement },
        { "Event", SyntaxKind.EventElement },
        { "EventDefinitionRef", SyntaxKind.BpmnAttributeToken },
        { "EventSubprocess", SyntaxKind.EventSubprocessElement },
        { "ExclusiveGateway", SyntaxKind.ExclusiveGatewayElement },
        { "ExpressionLanguage", SyntaxKind.BpmnAttributeToken },
        { "Exporter", SyntaxKind.BpmnAttributeToken },
        { "ExporterVersion", SyntaxKind.BpmnAttributeToken },
        { "Gateway", SyntaxKind.GatewayElement },
        { "GatewayDirection", SyntaxKind.BpmnAttributeToken },
        { "Group", SyntaxKind.GroupElement },
        { "Id", SyntaxKind.BpmnAttributeToken },
        { "Implementation", SyntaxKind.BpmnAttributeToken },
        { "ImportType", SyntaxKind.BpmnAttributeToken },
        { "IntermediateEvent", SyntaxKind.IntermediateEventElement },
        { "InputSet", SyntaxKind.BpmnAttributeToken },
        { "InitiatingParticipantRef", SyntaxKind.BpmnAttributeToken },
        { "IsClosed", SyntaxKind.BpmnAttributeToken },
        { "IsCollection", SyntaxKind.BpmnAttributeToken },
        { "IsForCompensation", SyntaxKind.BpmnAttributeToken },
        { "IsExecutable", SyntaxKind.BpmnAttributeToken },
        { "Lane", SyntaxKind.LaneElement },
        { "Location", SyntaxKind.BpmnAttributeToken },
        { "LoopType", SyntaxKind.BpmnAttributeToken },
        { "Link", SyntaxKind.LinkEventElement },
        { "Message", SyntaxKind.MessageEventElement },
        { "MessageEvent", SyntaxKind.MessageEventElement },
        { "MessageFlow", SyntaxKind.MessageFlowElement },
        { "Minus", SyntaxKind.MinusToken },
        { "Multiply", SyntaxKind.MultiplyToken },
        { "MustUnderstand", SyntaxKind.BpmnAttributeToken },
        { "Name", SyntaxKind.BpmnAttributeToken },
        { "Namespace", SyntaxKind.BpmnAttributeToken },
        { "OpenBrace", SyntaxKind.OpenBraceToken },
        { "OpenParenthesis", SyntaxKind.OpenParenthesisToken },
        { "OperationRef", SyntaxKind.BpmnAttributeToken },
        { "Ordering", SyntaxKind.BpmnAttributeToken },
        { "OutputSet", SyntaxKind.BpmnAttributeToken },
        { "ParallelGateway", SyntaxKind.ParallelGatewayElement },
        { "ParallelMultiple", SyntaxKind.BpmnAttributeToken },
        { "Plus", SyntaxKind.PlusToken },
        { "Pool", SyntaxKind.PoolElement },
        { "Process", SyntaxKind.BpmnProcessElement },
        { "ProcessRef", SyntaxKind.BpmnAttributeToken },
        { "ProcessType", SyntaxKind.BpmnAttributeToken },
        { "ScriptTask", SyntaxKind.ScriptTaskElement },
        { "SequenceFlow", SyntaxKind.SequenceFlowElement },
        { "ServiceTask", SyntaxKind.ServiceTaskElement },
        { "Signal", SyntaxKind.SignalEventElement },
        { "SourceRef", SyntaxKind.BpmnAttributeToken },
        { "StartEvent", SyntaxKind.StartEventElement },
        { "StartQuantity", SyntaxKind.BpmnAttributeToken },
        { "String", SyntaxKind.StringToken },
        { "Subprocess", SyntaxKind.SubprocessElement },
        { "StructureRef", SyntaxKind.BpmnAttributeToken },
        { "Use", SyntaxKind.BpmnAttributeToken },
        { "TargetNamespace", SyntaxKind.BpmnAttributeToken },
        { "TargetRef", SyntaxKind.BpmnAttributeToken },
        { "Task", SyntaxKind.TaskElement },
        { "TextAnnotation", SyntaxKind.TextAnnotationElement },
        { "TextFormat", SyntaxKind.BpmnAttributeToken },
        { "TriggeredByEvent", SyntaxKind.BpmnAttributeToken },
        { "Timer", SyntaxKind.TimerEventElement },
        { "TimerEvent", SyntaxKind.TimerEventElement },
        { "Type", SyntaxKind.BpmnAttributeToken },
        { "TypeLanguage", SyntaxKind.BpmnAttributeToken },
        { "UserTask", SyntaxKind.UserTaskElement },
        { "WaitForCompletion", SyntaxKind.BpmnAttributeToken },
        { "Whitespace", SyntaxKind.WhitespaceToken },
    };

    public static SyntaxKind GetKind(string text)
    {
        return Keywords.GetValueOrDefault(text, SyntaxKind.None);
    }
}