using Streamline.Domain.Schema.Activities;
using Streamline.Domain.Schema.Data;
using Streamline.Domain.Schema.Events;

namespace Streamline.Domain.Schema.Common;

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1182.0")]
[Serializable]
[System.Xml.Serialization.XmlTypeAttribute("tRootElement", Namespace="http://www.omg.org/spec/BPMN/20100524/MODEL")]
[System.Diagnostics.DebuggerStepThroughAttribute]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("rootElement", Namespace="http://www.omg.org/spec/BPMN/20100524/MODEL")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CallableElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Category))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Choreography))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Collaboration))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompensateEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionalEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrelationProperty))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataStore))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndPoint))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Escalation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EscalationEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalBusinessRuleTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalChoreographyTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalConversation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalManualTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalScriptTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalUserTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Interface))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Message))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartnerEntity))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartnerRole))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Process))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Resource))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Signal))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SignalEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminateEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimerEventDefinition))]
public abstract partial class RootElement : BaseElement;