// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Streamline.Infrastructure.Persistence;

#nullable disable

namespace Streamline.Infrastructure.Migrations
{
    [DbContext(typeof(StreamlineDbContext))]
    partial class StreamlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Streamline.Domain.Runtime.ActivityInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CalledProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateGroupIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateUserIds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowNodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowNodeName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CalledProcessInstanceId");

                    b.HasIndex("EndTime");

                    b.HasIndex("FlowNodeId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("StartTime");

                    b.HasIndex("State");

                    b.ToTable("ActivityInstances", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.EventSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventName");

                    b.HasIndex("EventType");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("ExecutionId1");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EventType", "EventName", "ExecutionId", "TenantId");

                    b.ToTable("EventSubscriptions", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFlowNodeId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsScope")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentFlowNodeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("ProcessInstanceId");

                    b.ToTable("Executions", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncidentTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("ExecutionId1");

                    b.HasIndex("IncidentTimestamp");

                    b.HasIndex("IncidentType");

                    b.HasIndex("JobId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TenantId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobHandlerConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobHandlerType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("ExecutionId1");

                    b.HasIndex("JobHandlerType");

                    b.HasIndex("LockExpirationTime");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("Retries");

                    b.HasIndex("TenantId");

                    b.HasIndex("LockOwner", "LockExpirationTime");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.ProcessInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessKey");

                    b.HasIndex("EndTime");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("StartTime");

                    b.HasIndex("State");

                    b.ToTable("ProcessInstances", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("Name");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("ProcessInstanceId", "ExecutionId", "Name")
                        .IsUnique();

                    b.ToTable("Variables", (string)null);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.ActivityInstance", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", "ProcessInstance")
                        .WithMany("ActivityInstances")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.EventSubscription", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.Execution", null)
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Streamline.Domain.Runtime.Execution", "Execution")
                        .WithMany()
                        .HasForeignKey("ExecutionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", null)
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Execution", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.Execution", "ParentExecution")
                        .WithMany()
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", "ProcessInstance")
                        .WithMany("Executions")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentExecution");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Incident", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.Execution", null)
                        .WithMany("Incidents")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamline.Domain.Runtime.Execution", "Execution")
                        .WithMany()
                        .HasForeignKey("ExecutionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamline.Domain.Runtime.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", null)
                        .WithMany("Incidents")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Job", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.Execution", null)
                        .WithMany("Jobs")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Streamline.Domain.Runtime.Execution", "Execution")
                        .WithMany()
                        .HasForeignKey("ExecutionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", null)
                        .WithMany("Jobs")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Variable", b =>
                {
                    b.HasOne("Streamline.Domain.Runtime.Execution", null)
                        .WithMany("Variables")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Streamline.Domain.Runtime.ProcessInstance", null)
                        .WithMany("Variables")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.Execution", b =>
                {
                    b.Navigation("EventSubscriptions");

                    b.Navigation("Incidents");

                    b.Navigation("Jobs");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Streamline.Domain.Runtime.ProcessInstance", b =>
                {
                    b.Navigation("ActivityInstances");

                    b.Navigation("EventSubscriptions");

                    b.Navigation("Executions");

                    b.Navigation("Incidents");

                    b.Navigation("Jobs");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
