<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Streamline.Domain\Streamline.Domain.csproj" />
    <!-- <ProjectReference Include="..\..\Streamline.Application\Streamline.Application.csproj" /> -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.2.2" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.13.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="NodaTime" Version="3.2.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Streamline.Engine</RootNamespace>
  </PropertyGroup>

</Project>
